query Products($first: Int) {
  products(first: $first) {
    nodes {
      title
      handle
      priceRange {
        maxVariantPrice {
          amount
        }
      }
      images(first: $first) {
        nodes {
          url
        }
      }
    }
  }
}

query Product($handle: String!, $first: Int!) {
  product(handle: $handle) {
    title
    handle
    media(first: $first) {
      nodes {
        previewImage {
          url(transform: { maxWidth: 400, maxHeight: 400 })
        }
      }
    }
    description
    variants(first: $first) {
      nodes {
        id
        priceV2 {
          amount
        }
      }
    }
    options {
      name
      values
    }
  }
}

query Cart($id: ID!, $first: Int) {
  cart(id: $id) {
    estimatedCost {
      totalAmount {
        amount
      }
    }
    lines(first: $first) {
      nodes {
        id
        quantity
        estimatedCost {
          totalAmount {
            amount
          }
        }
        merchandise {
          ... on ProductVariant {
            product {
              title
              featuredImage {
                url
              }
              variants(first: $first) {
                edges {
                  node {
                    priceV2 {
                      amount
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

mutation CartCreate($input: CartInput) {
  cartCreate(input: $input) {
    cart {
      id
    }
  }
}

mutation CartLinesAdd(
  $lines: [CartLineInput!]!
  $cartId: ID!
) {
  cartLinesAdd(lines: $lines, cartId: $cartId) {
    cart {
      id
    }
  }
}

query CartQuantity($id: ID!, $first: Int) {
  cart(id: $id) {
    lines(first: $first) {
      nodes {
        quantity
      }
    }
  }
}

mutation CartLinesUpdate(
  $cartId: ID!
  $lines: [CartLineUpdateInput!]!
) {
  cartLinesUpdate(cartId: $cartId, lines: $lines) {
    cart {
      id
    }
  }
}
